### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by Davidyao99** [Isabella98Liu/DG-Mesh#19]
Great Work!

I ran DG-Mesh on nerfies and received this cuda error. Any idea how to resolve this? I followed the build instructions using python 3.8 to avoid segmentation fault as suggested [here](https://github.com/Isabella98Liu/DG-Mesh/issues/8)

```
Update scale and center, new scale 0.22211025655269623, new center tensor([ 0.0109,  0.1050, -0.1813], device='cuda:0') [30/08 18:06:14]
Tensor occ torch.Size([256, 256, 256]) torch.float32 cuda:0 ∈ [0.0, 15.99420166015625] μ = 2.7302670787321404e-05 σ = 0.010541888885200024 [30/08 18:06:17]
/mnt/dgmesh/scene/gaussian_model_dpsr_dynamic_anchor.py:727: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  normals = torch.tensor(gs_normals, dtype=torch.float32, device="cuda")
DPSR normal initialization finished [30/08 18:06:18]
Training progress:  32%|████████████████████▊                                            | 8000/25001 [03:52<15:55, 17.80it/s, cycle_loss=0.0012, img_loss=0.0233, img_psnr=25.8696]Traceback (most recent call last):
  File "dgmesh/train.py", line 937, in <module>
    training(
  File "dgmesh/train.py", line 251, in training
    mask, mesh_image, verts, faces, _ = mesh_renderer(
  File "/mnt/dgmesh/utils/renderer.py", line 210, in mesh_renderer
    mask = render_mask(
  File "/mnt/dgmesh/utils/renderer.py", line 58, in render_mask
    rast_out, _ = dr.rasterize(glctx, v_pos_clip, mesh_t_pos_idx, resolution=resolution)
  File "/mnt/miniconda3/envs/dgmeshpy38/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/mnt/miniconda3/envs/dgmeshpy38/lib/python3.8/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/mnt/miniconda3/envs/dgmeshpy38/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 246, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]
```

**Comment by Davidyao99** [comment]
https://github.com/NVlabs/nvdiffrast/issues/131
